Reset='\033[0m'
Red='\033[0;31m'
Green='\033[0;32m'

function octo__help() {
  echo -e "Usage: $ProgramName ${Red}[command]${Reset} ${Green}<option>${Reset}"
  echo ""
  echo "Commands:"
  echo ""
  echo -e "    ${Red}help${Reset}"
  echo "         Display this help message."
  echo ""
  echo -e "    ${Red}connect${Reset}"
  echo "         Connect to printer via serial port."
  echo ""
  echo -e "    ${Red}disconnect${Reset}"
  echo "         Disconnect from printer."
  echo ""
  echo -e "    ${Red}connection${Reset}"
  echo "         Display connection status."
  echo ""
  echo -e "    ${Red}psu${Reset} ${Green}<on | off | toggle | reboot | status>${Reset}"
  echo "         Manage PSU state."
  echo "             Must have PSU Control plugin installed"
  echo "             & configured in your Octoprint instance."
  echo "               https://plugins.octoprint.org/plugins/psucontrol"
  echo "         Each of these PSU options can be sent as their own commands."
  echo -e "             e.g. $ProgramName ${Red}on${Reset}, ${Red}off${Reset}, ${Red}reboot${Reset}, etc."
  echo ""
  echo -e "    ${Red}gcode${Reset} ${Green}<'G-code Commands' | help>${Reset}"
  echo "         Send G-code commands (semicolon separated) to printer."
  echo -e "         ${Green}<help>${Reset}: Display link to Marlin G-code documentation."
  echo ""
  echo -e "    ${Red}select${Reset}"
  echo "         Select a file for printing from local storage."
  echo ""
  echo -e "    ${Red}unselect${Reset}"
  echo "         Unselect currently selected file."
  echo ""
  echo -e "    ${Red}job${Reset}"
  echo "         View current job status."
  echo ""
  echo -e "    ${Red}start${Reset}"
  echo "         Start currently selected print job."
  echo ""
  echo -e "    ${Red}cancel${Reset}"
  echo "         Abort currently running print job."
  echo ""
  echo -e "    ${Red}pause${Reset}"
  echo "         Pause currently running print job."
  echo ""
  echo -e "    ${Red}resume${Reset}"
  echo "         Resume currently paused print job."
  echo ""
  echo -e "    ${Red}time${Reset}"
  echo "         Display elapsed/remaining time for current print job."
  echo ""
  echo -e "    ${Red}bed${Reset} ${Green}<off | [value in °C] | status>${Reset}"
  echo "         Set heated bed temperature."
  echo ""
  echo -e "    ${Red}tool${Reset} ${Green}<off | [value in °C] | status>${Reset}"
  echo "         Set tool/hotend temperature."
  echo ""
  echo -e "    ${Red}fan${Reset} ${Green}<off | [0-100]% | [0-255]>${Reset}"
  echo "         Set cooling fan speed."
  echo ""
  echo -e "    ${Red}preheat${Reset} ${Green}<'profile name' | add | remove | list>${Reset}"
  echo "         Preheat bed/tool using values in the given preheat profile."
  echo ""
  echo -e "    ${Red}sleep${Reset} ${Green}<time in minutes>${Reset}"
  echo -e "         Display countdown timer for ${Green}<minutes>${Reset}."
  echo "         Useful for delaying subsequent commands."
  echo -e "             e.g. $ProgramName ${Red}sleep${Reset} ${Green}10${Reset} && $ProgramName ${Red}start${Reset}"
  echo "                  (sleep for 10 minutes, then start print job)"
  echo ""
}